### ISSUE TITLE
Nodecloud doesn't require or instantiate nodecloud plugin 

### ISSUE THREAD

**Issue by TheDhejavu** [leopardslab/nodecloud#32]
## Expected Behavior
The Nodecloud  base-provider.js needs to instantiate and require each and every provided plugin module via the `getProvider ` method 

After modifying the nodecloud `base-provider.js` module below. It works just fine

> /**
> 
>   Returns requested provider type

>   @param {Object} {provider - Type of provider - can be found here '/aws/provider'}
>   */
>   getProviders(options) {
>     if (ncConfig === undefined) {
>       throw new Error(
>         "Provider config file not found. Please create a config file in project root."
>       );
>     }
>     let providersToLoad = {};
>     
>       if (options && options.hasOwnProperty("overrideProviders") ) {
>         ncConfig.map(provider => {
>           const module = provider.plugin;
>             providersToLoad[provider.tag] = module(ncConfig.configPath);
>           });
>       } else {
> 
>         ncConfig.map(provider => {
>         if (!validProviders.includes(provider.name)) {
>           throw new Error("Provider not supported");
>         }
> 
>       const module = require(provider.libName);
>         providersToLoad[provider.tag] = new module(ncConfig.configPath);
>       });
>     }

## Actual Behavior

The current NodeCloud `base-provider.js` isn't compatible with NodeCLoud-Azure-Plugin, It throws error each and every time I try to start nodecloud-web

The below snippet of code is buggy and it throws error 

> /**
>    * Returns requested provider type
>    * @param {Object} {provider - Type of provider - can be found here '/aws/provider'}
>    */
>   getProviders(options) {
>     if (ncConfig === undefined) {
>       throw new Error(
>         "Provider config file not found. Please create a config file in project root."
>       );
>     }
> 
>     let providersToLoad = {};
> 
>     if (option && options.hasOwnProperty("overrideProviders")) {
>       ncConfig.map(provider => {
>         const module = provider.plugin;
>         providersToLoad[provider.tag] = module(provider.configPath);
>       });
>     } else {
>       ncConfig.map(provider => {
>         if (!validProviders.includes(provider.name)) {
>           throw new Error("Provider not supported");
>         }
> 
>         const module = provider.plugin;
>         providersToLoad[provider.tag] = module(provider.configPath);
>       });
>     }
> 
>     return providersToLoad;
>   }

![node1](https://user-images.githubusercontent.com/19678915/72390696-a6d01e80-372b-11ea-8cc4-f7b9f036ee28.PNG)
A screenshot of existing code and error

## Steps to Reproduce the Problem

 Follow Nodecloud-web installation guide 
https://github.com/cloudlibz/nodecloud-web

## Specifications

  - Version: 
  - Platform: Windows 10
  - Subsystem: node v10.16.2

**Comment by TheDhejavu** [comment]
There is a fix for this already @rehrumesh , i just need your take on this issue with the nodecloud and it's plugin

**Comment by rehrumesh** [comment]
@lakindu95 @rajikaimal Please look into this.
