### ISSUE TITLE
getProviders() - Wrong Function in README.md

### ISSUE THREAD

**Issue by angeryrohan** [leopardslab/nodecloud#6]
## Expected Behavior
<b>FIX: https://github.com/cloudlibz/nodecloud/pull/5</b>
We Expected to see the successful working of npm start, after setting up an app with nodecloud module

## Actual Behavior

![troi](https://user-images.githubusercontent.com/29266591/49702540-39e08000-fc1f-11e8-8982-dfed43f8010f.png)

## Steps to Reproduce the Problem

  1.Make a new nodeJS project by ```npm init```
  2. Inside your package.json, add nodecloud module ```"dependencies": {
    "nodecloud": "^0.1.0"
  }```
  3. Install dependencies by``` npm install ```
  4. Get a GCP key (link is given on the https://github.com/cloudlibz/nodecloud-gcp-plugin), download the key.json file and place it into your root folder.
  4.In your server.js (or your mainjsfile.js), include nodecloud module by typing in:
```
const nodeCloud = require("nodecloud");
// AWS
const gcpProviders = nodeCloud.getProviders('google', 'dronesym-app-ceabf26a2a7e.json');
const options = {
  apiVersion: "2016-11-15"
};
console.log(gcpProvider);

```
  5. Create a .nc.config.js file containing the code 
``` 
const providers = [
    {
        name: 'google',
        tag: 'google',
        libName: 'nodecloud-gcp-plugin',
        configFile: {
            projectId: "<your project ID>", //most probably will be "dronesym-app"
            keyFilename: "<path to your GCP Key JSON file>"
//GCP gives you the download of a pre-built key JSON file
        }
    },
    // other providers might be included here
]

module.exports = providers; 
```
  6. Run the code by going into the terminal, running ```node <yourfile>.js```
  7. Meet the error!

===x===

## How we found this error?
Me and @TheLukaszNs were discussing nodecloud related stuff on the gitter channel, When we both noticed an error on the same time, the code was simple, it just had to console.log(getProvider);
But changing getProvider() to getProviders() (as mentioned in readme.MD) would stop our code execution giving the above error. I've provided a fix for this^

**Comment by rajikaimal** [comment]
Hey did you refer to the latest documentation? Importing a plugin looks like this.

```js
const nodeCloud = require("nodecloud");
const ncProviders = nodeCloud.getProviders();
const options = {
  apiVersion: "2016-11-15"
};

const params = {
  ImageId: "ami-10fd7020", // amzn-ami-2011.09.1.x86_64-ebs
  InstanceType: "t1.micro",
  MinCount: 1,
  MaxCount: 1
};
const instanceParams = {
  Key: "Name",
  Value: "Node Cloud demo"
};
const ec2 = ncProviders.aws.compute(options);
```

**Comment by rajikaimal** [comment]
Closing this for now, feel free to open if you come across with a problem.
