### ISSUE TITLE
Creating a prettier Github action

### ISSUE THREAD

**Issue by rajitha1998** [leopardslab/nodecloud#70]
![image](https://user-images.githubusercontent.com/36359382/94982910-08574800-055c-11eb-9ddd-9b91b61869c8.png)

##  Welcome to NodeCloud with [Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/)! 
**Stay in the know:** Get notified of updates by clicking the 👁‍🗨 watch button and save the repository for later reference by clicking the ⭐️ star button at the top right corner of this repo! 

### Creating a prettier Github action 

Prettier is a very popular code formatter to format your code and prevent the ongoing debates about code styles.  Currently, prettier is triggered through a pre-commit hook ([husky](https://typicode.github.io/husky/#/))  which will run Prettier on the staged files prior to committing.  

This works well in most cases, but there are certain cases where the code might not be formatted:

- Running `git commit --no-verify` will commit code without running pre-commit hooks which can result in files not being formatted.

- Pre-commit hook ([husky](https://typicode.github.io/husky/#/)) is not properly installed in the developers local machine.

To automate this process you can use  [git auto-commit action ](https://github.com/stefanzweifel/git-auto-commit-action) to run prettier and commit the changes if necessary. Check out the references to get started 🚀! 

 
### Additional information

* The project currently contains two main branches: `master` and `nodecloud-next`. **This feature is required to the `nodecloud-next` branch. so make sure that you create the feature branch from `nodecloud-next`.** 

**`nodecloud-next:`** https://github.com/leopardslab/nodecloud/tree/nodecloud-next

* Be sure to sign up at https://hacktoberfest.digitalocean.com so you can qualify to pick a limited edition t-shirt 👚 or plant a tree 🌳!

* See https://hacktoberfest.digitalocean.com for more details

### Impact

*  Github workflows directory 

### References

* Helping [article](https://medium.com/@mskelton/auto-formatting-code-using-prettier-and-github-actions-ed458f58b7df) and [sample project ](https://github.com/mskelton/prettier-formatting-example) by @mskelton

* [git auto-commit action ](https://github.com/stefanzweifel/git-auto-commit-action) by @stefanzweifel

**Comment by mskelton** [comment]
Thanks for the shoutout on my article!  Excited to see someone pick up this issue for Hacktoberfest!

**Comment by stefanivic** [comment]
@rajitha1998 I don't wanna pick a "good first issue" as I am a more experienced developer, but if no one picks it up soon, I am interested in setting this up.

**Comment by lumenCodes** [comment]
> @rajitha1998 I don't wanna pick a "good first issue" as I am a more experienced developer, but if no one picks it up soon, I am interested in setting this up.

Ooh thanks.
I think I am here to pick it up. I am pretty new to contributing to open source.

**Comment by rajitha1998** [comment]
I will assign you to this task @lumenCodes :). Let us know if you need help when working on this.

**Comment by lumenCodes** [comment]
> I will assign you to this task @lumenCodes :). Let us know if you need help when working on this.

Ooh.

Thank you. I will sure reach out when I need help

**Comment by rajitha1998** [comment]
> > I will assign you to this task @lumenCodes :). Let us know if you need help when working on this.
> 
> Ooh.
> 
> Thank you. I will sure reach out when I need help

Hi @lumenCodes, any update on this? Do you need any help with the task?

**Comment by lumenCodes** [comment]
Yes I need help @rajitha1998 .

I am supposed to create the feature branch from `nodecloud-next` branch, but when I clone to my local I don't see the `nodecoud-next` branch

**Comment by rajitha1998** [comment]
Hey @lumenCodes, you need to fetch it from the upstream. 

Steps as follows,

1. Adding the upstream branch `git remote add upstream https://github.com/leopardslab/nodecloud.git`
2. Then, `git fetch upstream` to retrieve the new upstream branch
3. Then, `git checkout -b nodecloud-next upstream/nodecloud-next`
4. Finally, create a new branch from `nodecloud-next`

Reference: https://stackoverflow.com/questions/4410091/github-import-upstream-branch-into-fork

**Comment by lumenCodes** [comment]
Thank you very much ☺️ . I just made the PR. #73

**Comment by rajitha1998** [comment]
Fixed by #73
