### ISSUE TITLE
Typo errors in project documentation 

### ISSUE THREAD

**Issue by rajitha1998** [leopardslab/nodecloud#71]
![image](https://user-images.githubusercontent.com/36359382/94982910-08574800-055c-11eb-9ddd-9b91b61869c8.png)

##  Welcome to NodeCloud with [Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/)! 
**Stay in the know:** Get notified of updates by clicking the 👁‍🗨 watch button and save the repository for later reference by clicking the ⭐️ star button at the top right corner of this repo! 

### Some typo errors need to be fixed:

The `readme` [file](https://github.com/leopardslab/nodecloud/blob/nodecloud-next/README.md) of the `nodecloud-next` branch contains some typo errors. To note some (**typo error > correction**),

*  NodeCloud ☁️ is standard library >  NodeCloud ☁️ is  a standard library
*  providers with less code changes > providers with fewer code changes
* open source >  open-source
* community driven plugin > community-driven plugin,
* third party > third-party
* background knowlege on these > background knowledge on these
* This is where magic happens✨ > This is where the magic happens✨
* automactically  > automatically
*  immediatly > immediately 

These need to be corrected and if you identify more typo errors while reading, fix them as well. Feel free to add a comment for further clarifications!

### Additional information

* The project currently contains two main branches: `master` and `nodecloud-next`. **This feature is required to the `nodecloud-next` branch. so make sure that you create the feature branch from `nodecloud-next`.** 

**`nodecloud-next:`** https://github.com/leopardslab/nodecloud/tree/nodecloud-next.

* Be sure to sign up at https://hacktoberfest.digitalocean.com so you can qualify to pick a limited edition t-shirt 👚 or plant a tree 🌳!

* See https://hacktoberfest.digitalocean.com for more details.

* Add a comment below if you are interested, will assign the task.

### Impact

*  Read me file

## Knowledge required 

* Version control systems (git)

**Comment by ZenVega** [comment]
I would give it a shot. could u assign this to me?

**Comment by pr-db** [comment]
I would like to contribute to solving the issue, can you assign this to me?

**Comment by rajitha1998** [comment]
Hi @PRAy-d welcome to NodeCloud, this issue has been already taken. You can check for more good first issues once new issues are added to the Node Cloud project.

**Comment by mirnumaan** [comment]
can i help youwith more typo error if so ?

**Comment by mirnumaan** [comment]
Can I contribute for any other issue ?

**Comment by rajitha1998** [comment]
Solved with #72
